apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: flipkart-app-deployment
spec: # Defined the behaviour of the replicaset 
  replicas: 3
  selector: 
    matchLabels:
      web: flip
  template: # Pod Defination 
    metadata: 
      labels: 
        web: flip 
    spec: 
      containers:
        - name: flip-cont 
          image: muralisocial123/transaction-app:v1.0.0
          ports: 
            - containerPort: 8080   

